---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/_data/site.json
  label: Site Title and Headings
- type: heading
  label: Sections
- type: directory
  path: src/_includes/sections/section_content
  label: Section Content
  create: all
  match: "**/*"
- type: document
  path: src/_includes/sections/section_content/hero.md
  label: Hero
  match: "**/*"
upload_dir: src/assets
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
